server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: concrete
            client-secret: $2a$10$p9Pk0fQNAQSesI4vuvKA0OZanDD2
            resource-ids: resources
            scope: read,write

spring:
    #H2 Parameters
     datasource:
         url: jdbc:h2:oauth;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
         driver-class-name: org.h2.Driver
         platform: h2
         username: sa
         password:
         data: classpath:/sql/data.sql
         schema: classpath:/sql/schema.sql
     jpa:
         database-platform: org.hibernate.dialect.MySQLDialect
         generate-ddl: false
          hibernate:
              ddl-auto: create-drop
          show-sql: true
    #MySQL Parameters
    #  datasource:
    #      data: classpath:/sql/data.sql
    #      driver-class-name: com.mysql.jdbc.Driver 
    #      platform: mysql
    #      schema: classpath:/sql/schema.sql
    #      url: jdbc:mysql://localhost:3306/oauth?verifyServerCertificate=false&useSSL=false&requireSSL=false
    #      username: root
    #      password: 'root'
    #  jpa:
    #      database-platform: org.hibernate.dialect.MySQLDialect
    #      generate-ddl: false
    #      hibernate:
    #          ddl-auto: none
    #      show-sql: true