server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: concrete
            client-secret: $2a$10$ku5M0dkWfOhXU2tnA6DBYOuHSdXaltmChXKXFKiKWIgprCVpVPkSK
            resource-ids: resources
            scope: read,write

spring:
    datasource:
        data: classpath:/sql/data.sql
        schema: classpath:/sql/schema.sql
        url: jdbc:h2:mem:auth-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        platform: h2
        username: sa
        password:
        driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    #MySQL Config
    # datasource:
    #     data: classpath:/sql/data.sql
    #     driver-class-name: com.mysql.jdbc.Driver 
    #     platform: mysql
    #     schema: classpath:/sql/schema.sql
    #     url: jdbc:mysql://localhost:3306/oauth?verifyServerCertificate=false&useSSL=false&requireSSL=false
    #     username: root
    #     password: 'root'
    # jpa:
    #     database-platform: org.hibernate.dialect.MySQLDialect
    #     generate-ddl: false
    #     hibernate:
    #         ddl-auto: none
    #     show-sql: true
###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

