server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: concrete
            client-secret: $2a$10$r0RFDmpneBVryx.ihHK9gu6FFJQi4nTxQUqzdSTvrPpaKZMxigqpy
            resource-ids: resources
            scope: read,write

spring:
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
        platform: h2
        username: sa
        password:
        driverClassName: org.h2.Driver
        data: classpath:/sql/data.sql
        schema: classpath:/sql/schema.sql
        #driverClassName: com.mysql.jdbc.Driver
        #platform: mysql
        #driver-class-name: com.mysql.jdbc.Driver
        #url: jdbc:mysql://localhost/oauth?verifyServerCertificate=false&useSSL=false&requireSSL=false
        
    jpa:
        #database-platform: org.hibernate.dialect.MySQLDialect
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        #generate-ddl: false
        hibernate:
            #ddl-auto: create-drop
            ddl-auto: update 
        show-sql: true
        